### ISSUE TITLE
Написать инструкцию по деплою проекта на render.com

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#660]
### Problem description

Для демонстарции результата мы используем render.com, тк он бесплатный. 
Сейчас текущие инструкции заточены под heroku

### Proposed solution

Добавить инструкцию по деплою на render.com 
Проверить шаги. 
Что должно быть в итоге
1) работает аутентификация через github
2) тестовые данные загружены (фикстуры)
3) подключена бд рендера, все действия можно совершить, как на продакщене.

**Comment by usernaimandrey** [comment]
@fey там для рендера нужен конфигурационный файлик и скрипт(не обязателен но чтобы не писать на рендер калбасу из команд) может сразу в репу закинуть на CV как считаешь?

**Comment by fey** [comment]
@usernaimandrey да, можжно, тем более render предлагает использовать скрипты.
Можно глянуть в репо, где я делал деплой приложения на рельсе -  https://github.com/hexlet-components/rails-guestbook

**Comment by HelgiMagic** [comment]
куда эту инструкцию написать? в какой-то файл в этом репозитории? я новенький в open-source, не совсем понимаю, подскажите пожалуйста)

**Comment by usernaimandrey** [comment]
вот в этот https://github.com/Hexlet/hexlet-cv/blob/main/README.md

**Comment by fey** [comment]
Вы можете дописать в ридми файле, либо создать отдельный файл про деплой, если инструкция получается объемной.
пример, как это сделано в другом проекте - https://github.com/Hexlet/hexlet-friends#setup

**Comment by qsimpleq** [comment]
Есть большая проблема - ключ `config/credentials.yml.enc` в git уже лежит

Я могу страшный yml конфиг для `config/database.yml` написать

Но я либо меняю там окружение на dev и подменяю на постгрес, либо меняю ключ для production, что мне уже совсем не интересно

**Comment by qsimpleq** [comment]
Задача слишком сложная для джуна, ну честно

Я сделаю в рамках https://github.com/Hexlet/hexlet-cv/pull/677, но вот осадочек(

**Comment by qsimpleq** [comment]
Доку писать не буду, извините

**Comment by usernaimandrey** [comment]
там насколько я помню достаточно такого конфига
```yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: mysite_production
  username: mysite
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
```
но настоящий конфиг менять не надо, важно добавить конфиг для ренедера render.yml, bash скрипт для билда приложения и просто описать все шаги по пунктам, типа создатй базу, пропиши пременные окружения и тд.
